#!/usr/bin/env bash
# Повний automated cycle для task:
#   pre-pr:    tests → docs → commit → push → draft PR
#   post-merge: deploy lock → wait Coolify → smoke → close task
set -euo pipefail

TASK_ID="${1:-}"
MODE="${2:-pre-pr}"

if [ -z "$TASK_ID" ]; then
  TASK_ID=$(git branch --show-current | grep -oE 'task-[0-9]+' | head -1 || echo "")
  if [ -z "$TASK_ID" ]; then
    echo "Usage: $0 <task-id> [pre-pr|post-merge]"
    exit 1
  fi
fi

cd "$(git rev-parse --show-toplevel)"
TASK_TITLE=$(backlog task view "$TASK_ID" 2>/dev/null | grep "^Title:" | sed 's/^Title: //' || echo "$TASK_ID")
BRANCH=$(git branch --show-current)

echo "═══════════════════════════════════════════════"
echo "🔄 FULL CYCLE: $TASK_ID [$MODE]"
echo "   Branch: $BRANCH"
echo "   Title: $TASK_TITLE"
echo "═══════════════════════════════════════════════"

if [ "$MODE" = "pre-pr" ]; then

  echo ""
  echo "▶ Stage 1/5: Running tests..."
  bash scripts/run-tests.sh || { echo "🛑 Tests failed. NOT continuing cycle."; exit 1; }

  echo ""
  echo "▶ Stage 2/5: Updating docs..."
  bash scripts/update-docs.sh "$TASK_ID"

  echo ""
  echo "▶ Stage 3/5: Committing..."
  git add -A
  if git diff --cached --quiet; then
    echo "   (no changes to commit)"
  else
    git commit -m "feat($TASK_ID): $TASK_TITLE

Closes $TASK_ID

- Unit tests pass
- E2E tests pass
- Docs updated (CHANGELOG.md)"
  fi

  echo ""
  echo "▶ Stage 4/5: Pushing..."
  git push -u origin "$BRANCH" 2>/dev/null || git push

  echo ""
  echo "▶ Stage 5/5: Creating PR..."
  if ! gh pr view >/dev/null 2>&1; then
    TASK_DESC=$(backlog task view "$TASK_ID" 2>/dev/null | grep -A5 "^Description:" | tail -n +2 || echo "See task description.")
    gh pr create \
      --title "$TASK_TITLE" \
      --body "Closes $TASK_ID

## Summary
$TASK_TITLE

## What's done
$TASK_DESC

## Tests
- ✅ Unit tests: passed
- ✅ E2E tests: Playwright passed
- ✅ Docs updated: CHANGELOG.md

## Verification (after merge)
Automatic Coolify deploy + scripts/smoke.sh will run post-merge.

---
🤖 Generated by scripts/cycle.sh (pre-pr mode)" \
      --draft
    echo "   ✅ PR created (draft)"
  else
    echo "   (PR already exists)"
  fi

  # === Auto-labeling based on task labels ===
  if [ -n "$TASK_ID" ]; then
    TASK_LABELS=$(backlog task view "$TASK_ID" --format json 2>/dev/null | \
      jq -r '.labels // [] | join(",")' 2>/dev/null || \
      backlog task view "$TASK_ID" --plain 2>/dev/null | grep "^Labels:" | sed 's/^Labels: //' || echo "")
    echo "📋 Task labels: $TASK_LABELS"

    SAFE_LABELS="auto-merge docs docs-only deps ci-fix quick-win"
    BLOCK_LABELS="review-required breaking do-not-merge wip security"

    PR_LABEL="review-required"  # safe default

    for l in $SAFE_LABELS; do
      if echo ",$TASK_LABELS," | grep -qE ",$l,"; then
        PR_LABEL="auto-merge"
        echo "🤖 Safe label '$l' found → PR will auto-merge"
        break
      fi
    done

    for b in $BLOCK_LABELS; do
      if echo ",$TASK_LABELS," | grep -qE ",$b,"; then
        PR_LABEL="review-required"
        echo "✋ Blocking label '$b' found → manual review required"
        break
      fi
    done

    # Ensure label exists in repo
    if ! gh label list --json name --jq '.[].name' 2>/dev/null | grep -q "^${PR_LABEL}$"; then
      COLOR="0e8a16"
      [ "$PR_LABEL" = "review-required" ] && COLOR="d93f0b"
      gh label create "$PR_LABEL" --color "$COLOR" 2>/dev/null || true
    fi

    gh pr edit --add-label "$PR_LABEL" 2>/dev/null && \
      echo "✅ Applied label: $PR_LABEL" || \
      echo "⚠️ Could not apply label (PR may be draft)"
  fi

  echo ""
  echo "═══════════════════════════════════════════════"
  echo "✅ PRE-PR CYCLE COMPLETE. Ready for Sergiy review."
  echo "═══════════════════════════════════════════════"
  echo ""
  echo "Next: review PR → mark ready → merge → scripts/cycle.sh $TASK_ID post-merge"

elif [ "$MODE" = "post-merge" ]; then

  echo ""
  echo "▶ Post-merge 1/4: Acquiring deploy lock..."
  bash scripts/deploy-guard.sh

  echo ""
  echo "▶ Post-merge 2/4: Waiting Coolify deploy..."
  if [ -n "${COOLIFY_APP_UUID:-}" ]; then
    bash scripts/wait-deploy.sh 600 || { echo "🛑 Deploy failed"; exit 1; }
  else
    echo "   ⚠️ COOLIFY_APP_UUID not set. Skipping polling."
    sleep 60
  fi

  echo ""
  echo "▶ Post-merge 3/4: Production smoke..."
  bash scripts/smoke.sh "${PROD_URL:-https://app.ruta.cam}" || \
    { echo "🛑 Smoke failed"; exit 1; }

  echo ""
  echo "▶ Post-merge 4/4: Closing task..."
  backlog task edit "$TASK_ID" --status done
  echo "   ✅ $TASK_ID → done"

  echo ""
  echo "═══════════════════════════════════════════════"
  echo "✅ POST-MERGE CYCLE COMPLETE. Task $TASK_ID done."
  echo "═══════════════════════════════════════════════"

else
  echo "Unknown mode: $MODE. Use pre-pr or post-merge."
  exit 1
fi
